/**
 * Lista completa de exercícios por grupo muscular.
 * Nomes em português (terminologia brasileira de academia) e inglês.
 */

export interface Exercise {
  pt: string;
  en: string;
}

export const EXERCISES_BY_MUSCLE_GROUP: Record<string, Exercise[]> = {
  "Peito": [
    { pt: "Supino reto com barra", en: "Barbell Bench Press" },
    { pt: "Supino inclinado com barra", en: "Incline Barbell Bench Press" },
    { pt: "Supino declinado com barra", en: "Decline Barbell Bench Press" },
    { pt: "Supino reto com halteres", en: "Dumbbell Bench Press" },
    { pt: "Supino inclinado com halteres", en: "Incline Dumbbell Press" },
    { pt: "Crucifixo reto", en: "Dumbbell Fly" },
    { pt: "Crucifixo inclinado", en: "Incline Dumbbell Fly" },
    { pt: "Crossover (polia)", en: "Cable Crossover" },
    { pt: "Crossover baixo para cima", en: "Low-to-High Cable Crossover" },
    { pt: "Crossover alto para baixo", en: "High-to-Low Cable Crossover" },
    { pt: "Flexão de braços", en: "Push-Up" },
    { pt: "Flexão declinada", en: "Decline Push-Up" },
    { pt: "Supino na máquina (chest press)", en: "Machine Chest Press" },
    { pt: "Pec deck (voador máquina)", en: "Pec Deck Machine" },
    { pt: "Pullover com halter", en: "Dumbbell Pullover" },
    { pt: "Supino com pegada fechada", en: "Close-Grip Bench Press" },
    { pt: "Flexão com pegada aberta", en: "Wide Push-Up" },
    { pt: "Dip no paralelas (foco peito)", en: "Chest Dip" },
  ],

  "Costas": [
    { pt: "Barra fixa (pull-up)", en: "Pull-Up" },
    { pt: "Barra fixa pegada aberta", en: "Wide-Grip Pull-Up" },
    { pt: "Barra fixa pegada supinada (chin-up)", en: "Chin-Up" },
    { pt: "Puxada frontal na polia (lat pulldown)", en: "Lat Pulldown" },
    { pt: "Puxada frontal pegada aberta", en: "Wide-Grip Lat Pulldown" },
    { pt: "Puxada atrás da nuca", en: "Behind-the-Neck Lat Pulldown" },
    { pt: "Puxada com pegada neutra", en: "Neutral-Grip Lat Pulldown" },
    { pt: "Remada curvada com barra", en: "Barbell Bent-Over Row" },
    { pt: "Remada curvada com halter", en: "Dumbbell Bent-Over Row" },
    { pt: "Remada cavalinho (T-bar row)", en: "T-Bar Row" },
    { pt: "Remada unilateral com halter", en: "Single-Arm Dumbbell Row" },
    { pt: "Remada na máquina (seated row)", en: "Seated Cable Row" },
    { pt: "Remada na polia baixa", en: "Low Cable Row" },
    { pt: "Remada invertida (bodyweight)", en: "Inverted Row" },
    { pt: "Pulley frontal", en: "Seated Cable Row (wide grip)" },
    { pt: "Pulley triangular", en: "V-Bar Cable Row" },
    { pt: "Levantamento terra", en: "Deadlift" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Pull-over na polia", en: "Cable Pullover" },
    { pt: "Hiperextensão lombar", en: "Back Hyperextension" },
  ],

  "Ombros": [
    { pt: "Desenvolvimento militar com barra", en: "Overhead Barbell Press" },
    { pt: "Desenvolvimento com halteres sentado", en: "Seated Dumbbell Shoulder Press" },
    { pt: "Desenvolvimento com halteres em pé", en: "Standing Dumbbell Press" },
    { pt: "Desenvolvimento na máquina", en: "Machine Shoulder Press" },
    { pt: "Desenvolvimento Arnold", en: "Arnold Press" },
    { pt: "Elevação lateral com halteres", en: "Dumbbell Lateral Raise" },
    { pt: "Elevação lateral na polia", en: "Cable Lateral Raise" },
    { pt: "Elevação frontal com halteres", en: "Dumbbell Front Raise" },
    { pt: "Elevação frontal na polia", en: "Cable Front Raise" },
    { pt: "Elevação frontal com barra", en: "Barbell Front Raise" },
    { pt: "Elevação lateral inclinada", en: "Incline Dumbbell Lateral Raise" },
    { pt: "Crucifixo inverso (posterior de ombro)", en: "Reverse Dumbbell Fly" },
    { pt: "Face pull na polia", en: "Face Pull" },
    { pt: "Remada alta com barra", en: "Upright Barbell Row" },
    { pt: "Remada alta com halteres", en: "Upright Dumbbell Row" },
    { pt: "Encolhimento de ombros com halteres", en: "Dumbbell Shrug" },
    { pt: "Desenvolvimento com kettlebell", en: "Kettlebell Press" },
    { pt: "Push press", en: "Push Press" },
  ],

  "Bíceps": [
    { pt: "Rosca direta com barra reta", en: "Barbell Curl" },
    { pt: "Rosca direta com barra W (EZ)", en: "EZ-Bar Curl" },
    { pt: "Rosca alternada com halteres", en: "Alternating Dumbbell Curl" },
    { pt: "Rosca simultânea com halteres", en: "Dumbbell Curl (simultaneous)" },
    { pt: "Rosca concentrada", en: "Concentration Curl" },
    { pt: "Rosca martelo", en: "Hammer Curl" },
    { pt: "Rosca martelo na polia", en: "Cable Hammer Curl" },
    { pt: "Rosca scott (banco scott)", en: "Preacher Curl" },
    { pt: "Rosca scott com halter", en: "Dumbbell Preacher Curl" },
    { pt: "Rosca na polia baixa", en: "Cable Curl" },
    { pt: "Rosca no banco inclinado", en: "Incline Dumbbell Curl" },
    { pt: "Rosca 21", en: "21s Bicep Curl" },
    { pt: "Rosca spider", en: "Spider Curl" },
    { pt: "Rosca inversa com barra", en: "Reverse Barbell Curl" },
    { pt: "Rosca no cross (polia)", en: "Standing Cable Curl" },
    { pt: "Chin-up (foco bíceps)", en: "Chin-Up (biceps focus)" },
  ],

  "Tríceps": [
    { pt: "Tríceps testa com barra EZ", en: "EZ-Bar Skull Crusher" },
    { pt: "Tríceps testa com halteres", en: "Dumbbell Skull Crusher" },
    { pt: "Tríceps pulley (corda)", en: "Tricep Rope Pushdown" },
    { pt: "Tríceps pulley com barra reta", en: "Straight-Bar Tricep Pushdown" },
    { pt: "Tríceps pulley com barra V", en: "V-Bar Tricep Pushdown" },
    { pt: "Tríceps francês com halteres", en: "Overhead Dumbbell Tricep Extension" },
    { pt: "Tríceps francês na polia", en: "Overhead Cable Tricep Extension" },
    { pt: "Tríceps coice com halter", en: "Tricep Kickback" },
    { pt: "Mergulho no paralelas (foco tríceps)", en: "Tricep Dip" },
    { pt: "Supino pegada fechada", en: "Close-Grip Bench Press" },
    { pt: "Tríceps banco (fundo no banco)", en: "Bench Dip" },
    { pt: "Tríceps cross unilateral na polia", en: "Single-Arm Cable Pushdown" },
    { pt: "Tríceps martelo na polia", en: "Rope Hammer Pushdown" },
    { pt: "Tríceps com kettlebell overhead", en: "Kettlebell Overhead Tricep Extension" },
    { pt: "JM press", en: "JM Press" },
  ],

  "Antebraço": [
    { pt: "Rosca punho com barra (flexão de punho)", en: "Barbell Wrist Curl" },
    { pt: "Rosca punho com halteres", en: "Dumbbell Wrist Curl" },
    { pt: "Rosca punho inversa com barra", en: "Reverse Barbell Wrist Curl" },
    { pt: "Rosca punho inversa com halteres", en: "Reverse Dumbbell Wrist Curl" },
    { pt: "Rosca punho atrás das costas", en: "Behind-the-Back Wrist Curl" },
    { pt: "Farmer's walk (caminhada do fazendeiro)", en: "Farmer's Walk" },
    { pt: "Agarrar bola de tênis/apertador de mão", en: "Grip Strengthener / Hand Gripper" },
    { pt: "Rosca martelo na polia (corda)", en: "Cable Rope Hammer Curl" },
    { pt: "Dead hang (pendurar na barra)", en: "Dead Hang" },
    { pt: "Plate pinch (segurar anilha de pé)", en: "Plate Pinch Hold" },
    { pt: "Rosca inversa na polia", en: "Reverse Cable Curl" },
    { pt: "Wrist roller (enrolador de punho)", en: "Wrist Roller" },
    { pt: "Extensão de punho com halter", en: "Dumbbell Wrist Extension" },
    { pt: "Towel pull-up (barra com toalha)", en: "Towel Pull-Up" },
    { pt: "Rice bucket (balde de arroz)", en: "Rice Bucket Training" },
  ],

  "Abdômen": [
    { pt: "Abdominal no solo (crunch)", en: "Crunch" },
    { pt: "Abdominal infra (elevação de pernas deitado)", en: "Lying Leg Raise" },
    { pt: "Abdominal infra no banco declinado", en: "Decline Bench Leg Raise" },
    { pt: "Prancha frontal", en: "Plank" },
    { pt: "Prancha lateral", en: "Side Plank" },
    { pt: "Abdominal no aparelho (crunch machine)", en: "Machine Crunch" },
    { pt: "Abdominal na polia alta (cable crunch)", en: "Cable Crunch" },
    { pt: "Abdominal bicicleta", en: "Bicycle Crunch" },
    { pt: "Abdominal remador", en: "V-Up" },
    { pt: "Elevação de pernas na barra fixa", en: "Hanging Leg Raise" },
    { pt: "Elevação de joelhos na barra fixa", en: "Hanging Knee Raise" },
    { pt: "Abdominal oblíquo (twist russo)", en: "Russian Twist" },
    { pt: "Mountain climber", en: "Mountain Climber" },
    { pt: "Abdominal com roda (ab wheel)", en: "Ab Wheel Rollout" },
    { pt: "Pallof press na polia", en: "Pallof Press" },
    { pt: "Woodchopper na polia", en: "Cable Woodchop" },
    { pt: "Toe touch deitado", en: "Lying Toe Touch" },
    { pt: "Dragon flag", en: "Dragon Flag" },
  ],

  "Quadríceps": [
    { pt: "Agachamento livre com barra", en: "Barbell Back Squat" },
    { pt: "Agachamento frontal", en: "Front Squat" },
    { pt: "Agachamento no smith", en: "Smith Machine Squat" },
    { pt: "Agachamento no hack machine", en: "Hack Squat Machine" },
    { pt: "Leg press 45°", en: "Leg Press 45°" },
    { pt: "Leg press horizontal", en: "Horizontal Leg Press" },
    { pt: "Cadeira extensora", en: "Leg Extension" },
    { pt: "Avanço (lunges) com halteres", en: "Dumbbell Lunge" },
    { pt: "Avanço com barra", en: "Barbell Lunge" },
    { pt: "Búlgaro (agachamento búlgaro)", en: "Bulgarian Split Squat" },
    { pt: "Passada (walking lunge)", en: "Walking Lunge" },
    { pt: "Agachamento sumô", en: "Sumo Squat" },
    { pt: "Agachamento goblet", en: "Goblet Squat" },
    { pt: "Pistol squat (agachamento unilateral)", en: "Pistol Squat" },
    { pt: "Step up com halteres", en: "Dumbbell Step-Up" },
    { pt: "Agachamento sissy", en: "Sissy Squat" },
    { pt: "Wall sit (agachamento isométrico na parede)", en: "Wall Sit" },
    { pt: "Agachamento com kettlebell", en: "Kettlebell Squat" },
  ],

  "Posterior de Coxa": [
    { pt: "Mesa flexora (lying leg curl)", en: "Lying Leg Curl" },
    { pt: "Cadeira flexora (seated leg curl)", en: "Seated Leg Curl" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Levantamento terra stiff", en: "Stiff-Leg Deadlift" },
    { pt: "Levantamento terra convencional", en: "Conventional Deadlift" },
    { pt: "Bom dia (good morning)", en: "Good Morning" },
    { pt: "Agachamento com barra baixa", en: "Low Bar Squat" },
    { pt: "Nordic curl (flexão nórdica)", en: "Nordic Ham Curl" },
    { pt: "Stiff com halteres", en: "Dumbbell Stiff-Leg Deadlift" },
    { pt: "Stiff com kettlebell", en: "Kettlebell Stiff-Leg Deadlift" },
    { pt: "Ponte de glúteos unilateral", en: "Single-Leg Glute Bridge" },
    { pt: "Flexão nórdica reversa", en: "Reverse Nordic Curl" },
    { pt: "Glute ham raise", en: "Glute Ham Raise" },
    { pt: "Levantamento terra sumô", en: "Sumo Deadlift" },
    { pt: "Pull-through na polia", en: "Cable Pull-Through" },
    { pt: "Slider leg curl", en: "Slider Leg Curl" },
  ],

  "Glúteos": [
    { pt: "Agachamento livre com barra", en: "Barbell Back Squat" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Hip thrust com barra", en: "Barbell Hip Thrust" },
    { pt: "Hip thrust na máquina", en: "Machine Hip Thrust" },
    { pt: "Ponte de glúteos", en: "Glute Bridge" },
    { pt: "Ponte de glúteos com barra", en: "Barbell Glute Bridge" },
    { pt: "Cable pull-through", en: "Cable Pull-Through" },
    { pt: "Avanço (lunge)", en: "Lunge" },
    { pt: "Agachamento búlgaro", en: "Bulgarian Split Squat" },
    { pt: "Step up com halteres", en: "Dumbbell Step-Up" },
    { pt: "Abdução de quadril na máquina", en: "Hip Abduction Machine" },
    { pt: "Abdução com faixa elástica", en: "Banded Hip Abduction" },
    { pt: "Clamshell com faixa", en: "Banded Clamshell" },
    { pt: "Donkey kick na polia", en: "Cable Donkey Kick" },
    { pt: "Fire hydrant", en: "Fire Hydrant" },
    { pt: "Coice na polia (cable kickback)", en: "Cable Glute Kickback" },
    { pt: "Agachamento sumô", en: "Sumo Squat" },
    { pt: "Kettlebell swing", en: "Kettlebell Swing" },
  ],

  "Panturrilha": [
    { pt: "Elevação de panturrilha em pé (gêmeos)", en: "Standing Calf Raise" },
    { pt: "Elevação de panturrilha sentado", en: "Seated Calf Raise" },
    { pt: "Elevação de panturrilha no leg press", en: "Leg Press Calf Raise" },
    { pt: "Elevação de panturrilha no smith", en: "Smith Machine Calf Raise" },
    { pt: "Elevação de panturrilha unilateral em pé", en: "Single-Leg Standing Calf Raise" },
    { pt: "Elevação de panturrilha na máquina", en: "Calf Raise Machine" },
    { pt: "Elevação de panturrilha no degrau (step)", en: "Step Calf Raise" },
    { pt: "Elevação de panturrilha com halteres", en: "Dumbbell Calf Raise" },
    { pt: "Donkey calf raise", en: "Donkey Calf Raise" },
    { pt: "Elevação de panturrilha com barra", en: "Barbell Calf Raise" },
    { pt: "Saltos (jump rope)", en: "Jump Rope" },
    { pt: "Pogo jump", en: "Pogo Jump" },
    { pt: "Elevação de panturrilha no hack", en: "Hack Squat Calf Raise" },
    { pt: "Tibialis anterior raise", en: "Tibialis Anterior Raise" },
  ],

  "Trapézio": [
    { pt: "Encolhimento com barra (shrug)", en: "Barbell Shrug" },
    { pt: "Encolhimento com halteres", en: "Dumbbell Shrug" },
    { pt: "Encolhimento no smith", en: "Smith Machine Shrug" },
    { pt: "Encolhimento na máquina de encolhimento", en: "Shrug Machine" },
    { pt: "Encolhimento com kettlebell", en: "Kettlebell Shrug" },
    { pt: "Encolhimento com trap bar", en: "Trap Bar Shrug" },
    { pt: "Remada alta com barra", en: "Barbell Upright Row" },
    { pt: "Remada alta com halteres", en: "Dumbbell Upright Row" },
    { pt: "Face pull na polia", en: "Face Pull" },
    { pt: "Encolhimento na polia baixa", en: "Cable Shrug" },
    { pt: "Encolhimento por trás das costas", en: "Behind-the-Back Barbell Shrug" },
    { pt: "Farmer's walk", en: "Farmer's Walk" },
    { pt: "Overhead carry (caminhada acima da cabeça)", en: "Overhead Carry" },
    { pt: "Power clean", en: "Power Clean" },
    { pt: "Clean and press", en: "Clean and Press" },
    { pt: "Scaption com halteres", en: "Scaption" },
  ],
};
