/**
 * Lista completa de exercícios por grupo muscular.
 * Nomes em português (terminologia brasileira de academia) e inglês.
 */

export interface Exercise {
  pt: string;
  en: string;
}

export const EXERCISES_BY_MUSCLE_GROUP: Record<string, Exercise[]> = {
  "Peito": [
    { pt: "Supino reto com barra", en: "Barbell Bench Press" },
    { pt: "Supino inclinado com barra", en: "Incline Barbell Bench Press" },
    { pt: "Supino declinado com barra", en: "Decline Barbell Bench Press" },
    { pt: "Supino reto com halteres", en: "Dumbbell Bench Press" },
    { pt: "Supino inclinado com halteres", en: "Incline Dumbbell Press" },
    { pt: "Crucifixo reto", en: "Dumbbell Fly" },
    { pt: "Crucifixo inclinado", en: "Incline Dumbbell Fly" },
    { pt: "Crossover (polia)", en: "Cable Crossover" },
    { pt: "Crossover baixo para cima", en: "Low-to-High Cable Crossover" },
    { pt: "Crossover alto para baixo", en: "High-to-Low Cable Crossover" },
    { pt: "Flexão de braços", en: "Push-Up" },
    { pt: "Flexão declinada", en: "Decline Push-Up" },
    { pt: "Supino na máquina (chest press)", en: "Machine Chest Press" },
    { pt: "Pec deck (voador máquina)", en: "Pec Deck Machine" },
    { pt: "Pullover com halter", en: "Dumbbell Pullover" },
    { pt: "Supino com pegada fechada", en: "Close-Grip Bench Press" },
    { pt: "Flexão com pegada aberta", en: "Wide Push-Up" },
    { pt: "Dip no paralelas (foco peito)", en: "Chest Dip" },
    { pt: "Supino declinado com halteres", en: "Decline Dumbbell Bench Press" },
    { pt: "Crucifixo declinado", en: "Decline Dumbbell Fly" },
    { pt: "Crucifixo na polia (banco reto)", en: "Flat Bench Cable Fly" },
    { pt: "Crucifixo unilateral na polia", en: "Single-Arm Cable Crossover" },
    { pt: "Supino no smith", en: "Smith Machine Bench Press" },
    { pt: "Supino inclinado no smith", en: "Smith Machine Incline Press" },
    { pt: "Supino declinado no smith", en: "Smith Machine Decline Press" },
    { pt: "Chest press inclinado na máquina", en: "Incline Machine Chest Press" },
    { pt: "Supino com halteres pegada neutra", en: "Neutral-Grip Dumbbell Press" },
    { pt: "Floor press (supino no chão)", en: "Floor Press" },
    { pt: "Flexão inclinada (mãos elevadas)", en: "Incline Push-Up" },
    { pt: "Flexão diamante", en: "Diamond Push-Up" },
    { pt: "Flexão com pés elevados", en: "Feet-Elevated Push-Up" },
    { pt: "Svend press (pressão de anilha)", en: "Svend Press" },
  ],

  "Costas": [
    { pt: "Barra fixa (pull-up)", en: "Pull-Up" },
    { pt: "Barra fixa pegada aberta", en: "Wide-Grip Pull-Up" },
    { pt: "Barra fixa pegada supinada (chin-up)", en: "Chin-Up" },
    { pt: "Puxada frontal na polia (lat pulldown)", en: "Lat Pulldown" },
    { pt: "Puxada frontal pegada aberta", en: "Wide-Grip Lat Pulldown" },
    { pt: "Puxada atrás da nuca", en: "Behind-the-Neck Lat Pulldown" },
    { pt: "Puxada com pegada neutra", en: "Neutral-Grip Lat Pulldown" },
    { pt: "Remada curvada com barra", en: "Barbell Bent-Over Row" },
    { pt: "Remada curvada com halter", en: "Dumbbell Bent-Over Row" },
    { pt: "Remada cavalinho (T-bar row)", en: "T-Bar Row" },
    { pt: "Remada unilateral com halter", en: "Single-Arm Dumbbell Row" },
    { pt: "Remada na máquina (seated row)", en: "Seated Cable Row" },
    { pt: "Remada na polia baixa", en: "Low Cable Row" },
    { pt: "Remada invertida (bodyweight)", en: "Inverted Row" },
    { pt: "Pulley frontal", en: "Seated Cable Row (wide grip)" },
    { pt: "Pulley triangular", en: "V-Bar Cable Row" },
    { pt: "Levantamento terra", en: "Deadlift" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Pull-over na polia", en: "Cable Pullover" },
    { pt: "Hiperextensão lombar", en: "Back Hyperextension" },
    { pt: "Remada curvada pegada supinada", en: "Reverse-Grip Bent-Over Row" },
    { pt: "Remada no smith", en: "Smith Machine Row" },
    { pt: "Remada articulada na máquina", en: "Leverage Machine Row" },
    { pt: "Remada serrote apoiado no banco inclinado", en: "Chest-Supported Dumbbell Row" },
    { pt: "Remada com kettlebell unilateral", en: "One-Arm Kettlebell Row" },
    { pt: "Remada renegada", en: "Renegade Row" },
    { pt: "Puxada unilateral na polia", en: "Single-Arm Lat Pulldown" },
    { pt: "Puxada com braços estendidos (pulldown)", en: "Straight-Arm Pulldown" },
    { pt: "Barra fixa pegada neutra", en: "Neutral-Grip Pull-Up" },
    { pt: "Barra fixa com peso", en: "Weighted Pull-Up" },
    { pt: "Muscle-up", en: "Muscle-Up" },
    { pt: "Rack pull", en: "Rack Pull" },
    { pt: "Levantamento terra com déficit", en: "Deficit Deadlift" },
    { pt: "Levantamento terra com trap bar", en: "Trap Bar Deadlift" },
  ],

  "Ombros": [
    { pt: "Desenvolvimento militar com barra", en: "Overhead Barbell Press" },
    { pt: "Desenvolvimento com halteres sentado", en: "Seated Dumbbell Shoulder Press" },
    { pt: "Desenvolvimento com halteres em pé", en: "Standing Dumbbell Press" },
    { pt: "Desenvolvimento na máquina", en: "Machine Shoulder Press" },
    { pt: "Desenvolvimento Arnold", en: "Arnold Press" },
    { pt: "Elevação lateral com halteres", en: "Dumbbell Lateral Raise" },
    { pt: "Elevação lateral na polia", en: "Cable Lateral Raise" },
    { pt: "Elevação frontal com halteres", en: "Dumbbell Front Raise" },
    { pt: "Elevação frontal na polia", en: "Cable Front Raise" },
    { pt: "Elevação frontal com barra", en: "Barbell Front Raise" },
    { pt: "Elevação lateral inclinada", en: "Incline Dumbbell Lateral Raise" },
    { pt: "Crucifixo inverso (posterior de ombro)", en: "Reverse Dumbbell Fly" },
    { pt: "Face pull na polia", en: "Face Pull" },
    { pt: "Remada alta com barra", en: "Upright Barbell Row" },
    { pt: "Remada alta com halteres", en: "Upright Dumbbell Row" },
    { pt: "Encolhimento de ombros com halteres", en: "Dumbbell Shrug" },
    { pt: "Desenvolvimento com kettlebell", en: "Kettlebell Press" },
    { pt: "Push press", en: "Push Press" },
    { pt: "Desenvolvimento no smith", en: "Smith Machine Shoulder Press" },
    { pt: "Elevação lateral na máquina", en: "Machine Lateral Raise" },
    { pt: "Crucifixo inverso na polia", en: "Cable Rear Delt Fly" },
    { pt: "Crucifixo inverso na máquina (voador inverso)", en: "Reverse Pec Deck" },
    { pt: "Elevação frontal com anilha", en: "Front Plate Raise" },
    { pt: "Rotação externa na polia", en: "Cable External Rotation" },
    { pt: "Rotação externa com faixa", en: "Band External Rotation" },
    { pt: "Band pull-apart", en: "Band Pull-Apart" },
    { pt: "Desenvolvimento cubano", en: "Cuban Press" },
    { pt: "Landmine press", en: "Landmine Press" },
    { pt: "Flexão pino (handstand push-up)", en: "Handstand Push-Up" },
    { pt: "Elevação em Y no banco inclinado", en: "Incline Y-Raise" },
  ],

  "Bíceps": [
    { pt: "Rosca direta com barra reta", en: "Barbell Curl" },
    { pt: "Rosca direta com barra W (EZ)", en: "EZ-Bar Curl" },
    { pt: "Rosca alternada com halteres", en: "Alternating Dumbbell Curl" },
    { pt: "Rosca simultânea com halteres", en: "Dumbbell Curl (simultaneous)" },
    { pt: "Rosca concentrada", en: "Concentration Curl" },
    { pt: "Rosca martelo", en: "Hammer Curl" },
    { pt: "Rosca martelo na polia", en: "Cable Hammer Curl" },
    { pt: "Rosca scott (banco scott)", en: "Preacher Curl" },
    { pt: "Rosca scott com halter", en: "Dumbbell Preacher Curl" },
    { pt: "Rosca na polia baixa", en: "Cable Curl" },
    { pt: "Rosca no banco inclinado", en: "Incline Dumbbell Curl" },
    { pt: "Rosca 21", en: "21s Bicep Curl" },
    { pt: "Rosca spider", en: "Spider Curl" },
    { pt: "Rosca inversa com barra", en: "Reverse Barbell Curl" },
    { pt: "Rosca no cross (polia)", en: "Standing Cable Curl" },
    { pt: "Chin-up (foco bíceps)", en: "Chin-Up (biceps focus)" },
    { pt: "Rosca drag", en: "Drag Curl" },
    { pt: "Rosca Zottman", en: "Zottman Curl" },
    { pt: "Rosca na máquina", en: "Machine Bicep Curl" },
    { pt: "Rosca scott na máquina", en: "Machine Preacher Curl" },
    { pt: "Rosca martelo no banco inclinado", en: "Incline Hammer Curl" },
    { pt: "Rosca martelo cruzada (cross body)", en: "Cross-Body Hammer Curl" },
    { pt: "Rosca na polia alta (dupla)", en: "High Cable Curl" },
    { pt: "Rosca direta pegada fechada", en: "Close-Grip Barbell Curl" },
    { pt: "Rosca direta pegada aberta", en: "Wide-Grip Barbell Curl" },
    { pt: "Rosca deitado na polia baixa", en: "Lying Cable Curl" },
  ],

  "Tríceps": [
    { pt: "Tríceps testa com barra EZ", en: "EZ-Bar Skull Crusher" },
    { pt: "Tríceps testa com halteres", en: "Dumbbell Skull Crusher" },
    { pt: "Tríceps pulley (corda)", en: "Tricep Rope Pushdown" },
    { pt: "Tríceps pulley com barra reta", en: "Straight-Bar Tricep Pushdown" },
    { pt: "Tríceps pulley com barra V", en: "V-Bar Tricep Pushdown" },
    { pt: "Tríceps francês com halteres", en: "Overhead Dumbbell Tricep Extension" },
    { pt: "Tríceps francês na polia", en: "Overhead Cable Tricep Extension" },
    { pt: "Tríceps coice com halter", en: "Tricep Kickback" },
    { pt: "Mergulho no paralelas (foco tríceps)", en: "Tricep Dip" },
    { pt: "Supino pegada fechada", en: "Close-Grip Bench Press" },
    { pt: "Tríceps banco (fundo no banco)", en: "Bench Dip" },
    { pt: "Tríceps cross unilateral na polia", en: "Single-Arm Cable Pushdown" },
    { pt: "Tríceps martelo na polia", en: "Rope Hammer Pushdown" },
    { pt: "Tríceps com kettlebell overhead", en: "Kettlebell Overhead Tricep Extension" },
    { pt: "JM press", en: "JM Press" },
    { pt: "Tríceps na máquina (extensão)", en: "Machine Tricep Extension" },
    { pt: "Mergulho na máquina (dip machine)", en: "Machine Dip" },
    { pt: "Extensão de tríceps deitado na polia", en: "Cable Lying Tricep Extension" },
    { pt: "Tríceps francês unilateral com halter", en: "Single-Arm Overhead Dumbbell Extension" },
    { pt: "Tríceps pulley pegada inversa", en: "Reverse-Grip Tricep Pushdown" },
    { pt: "Flexão diamante (foco tríceps)", en: "Diamond Push-Up (triceps focus)" },
    { pt: "Floor press com halteres", en: "Dumbbell Floor Press" },
    { pt: "Extensão de tríceps declinado com barra EZ", en: "Decline EZ-Bar Tricep Extension" },
    { pt: "Supino fechado no smith", en: "Smith Machine Close-Grip Bench Press" },
    { pt: "Extensão com barra por trás da cabeça em pé", en: "Standing Overhead Barbell Extension" },
  ],

  "Antebraço": [
    { pt: "Rosca punho com barra (flexão de punho)", en: "Barbell Wrist Curl" },
    { pt: "Rosca punho com halteres", en: "Dumbbell Wrist Curl" },
    { pt: "Rosca punho inversa com barra", en: "Reverse Barbell Wrist Curl" },
    { pt: "Rosca punho inversa com halteres", en: "Reverse Dumbbell Wrist Curl" },
    { pt: "Rosca punho atrás das costas", en: "Behind-the-Back Wrist Curl" },
    { pt: "Farmer's walk (caminhada do fazendeiro)", en: "Farmer's Walk" },
    { pt: "Agarrar bola de tênis/apertador de mão", en: "Grip Strengthener / Hand Gripper" },
    { pt: "Rosca martelo na polia (corda)", en: "Cable Rope Hammer Curl" },
    { pt: "Dead hang (pendurar na barra)", en: "Dead Hang" },
    { pt: "Plate pinch (segurar anilha de pé)", en: "Plate Pinch Hold" },
    { pt: "Rosca inversa na polia", en: "Reverse Cable Curl" },
    { pt: "Wrist roller (enrolador de punho)", en: "Wrist Roller" },
    { pt: "Extensão de punho com halter", en: "Dumbbell Wrist Extension" },
    { pt: "Towel pull-up (barra com toalha)", en: "Towel Pull-Up" },
    { pt: "Rice bucket (balde de arroz)", en: "Rice Bucket Training" },
    { pt: "Rosca punho na polia", en: "Cable Wrist Curl" },
    { pt: "Flexão de dedos com barra", en: "Barbell Finger Curl" },
    { pt: "Pronação com halter deitado", en: "Dumbbell Lying Pronation" },
    { pt: "Supinação com halter deitado", en: "Dumbbell Lying Supination" },
    { pt: "Suitcase carry (caminhada unilateral)", en: "Suitcase Carry" },
    { pt: "Aperto de anilhas em pé", en: "Plate Hand Squeeze" },
  ],

  "Abdômen": [
    { pt: "Abdominal no solo (crunch)", en: "Crunch" },
    { pt: "Abdominal infra (elevação de pernas deitado)", en: "Lying Leg Raise" },
    { pt: "Abdominal infra no banco declinado", en: "Decline Bench Leg Raise" },
    { pt: "Prancha frontal", en: "Plank" },
    { pt: "Prancha lateral", en: "Side Plank" },
    { pt: "Abdominal no aparelho (crunch machine)", en: "Machine Crunch" },
    { pt: "Abdominal na polia alta (cable crunch)", en: "Cable Crunch" },
    { pt: "Abdominal bicicleta", en: "Bicycle Crunch" },
    { pt: "Abdominal remador", en: "V-Up" },
    { pt: "Elevação de pernas na barra fixa", en: "Hanging Leg Raise" },
    { pt: "Elevação de joelhos na barra fixa", en: "Hanging Knee Raise" },
    { pt: "Abdominal oblíquo (twist russo)", en: "Russian Twist" },
    { pt: "Mountain climber", en: "Mountain Climber" },
    { pt: "Abdominal com roda (ab wheel)", en: "Ab Wheel Rollout" },
    { pt: "Pallof press na polia", en: "Pallof Press" },
    { pt: "Woodchopper na polia", en: "Cable Woodchop" },
    { pt: "Toe touch deitado", en: "Lying Toe Touch" },
    { pt: "Dragon flag", en: "Dragon Flag" },
    { pt: "Abdominal completo (sit-up)", en: "Sit-Up" },
    { pt: "Abdominal declinado", en: "Decline Crunch" },
    { pt: "Abdominal na bola suíça", en: "Exercise Ball Crunch" },
    { pt: "Abdominal reverso", en: "Reverse Crunch" },
    { pt: "Dead bug", en: "Dead Bug" },
    { pt: "Bird dog", en: "Bird Dog" },
    { pt: "Hollow hold", en: "Hollow Body Hold" },
    { pt: "Elevação de pernas na paralela (captain's chair)", en: "Captain's Chair Leg Raise" },
    { pt: "Flexão lateral com halter", en: "Dumbbell Side Bend" },
    { pt: "Landmine 180 (rotação com barra)", en: "Landmine 180" },
    { pt: "L-sit", en: "L-Sit" },
    { pt: "Toes to bar", en: "Toes to Bar" },
  ],

  "Quadríceps": [
    { pt: "Agachamento livre com barra", en: "Barbell Back Squat" },
    { pt: "Agachamento frontal", en: "Front Squat" },
    { pt: "Agachamento no smith", en: "Smith Machine Squat" },
    { pt: "Agachamento no hack machine", en: "Hack Squat Machine" },
    { pt: "Leg press 45°", en: "Leg Press 45°" },
    { pt: "Leg press horizontal", en: "Horizontal Leg Press" },
    { pt: "Cadeira extensora", en: "Leg Extension" },
    { pt: "Avanço (lunges) com halteres", en: "Dumbbell Lunge" },
    { pt: "Avanço com barra", en: "Barbell Lunge" },
    { pt: "Búlgaro (agachamento búlgaro)", en: "Bulgarian Split Squat" },
    { pt: "Passada (walking lunge)", en: "Walking Lunge" },
    { pt: "Agachamento sumô", en: "Sumo Squat" },
    { pt: "Agachamento goblet", en: "Goblet Squat" },
    { pt: "Pistol squat (agachamento unilateral)", en: "Pistol Squat" },
    { pt: "Step up com halteres", en: "Dumbbell Step-Up" },
    { pt: "Agachamento sissy", en: "Sissy Squat" },
    { pt: "Wall sit (agachamento isométrico na parede)", en: "Wall Sit" },
    { pt: "Agachamento com kettlebell", en: "Kettlebell Squat" },
    { pt: "Agachamento livre corporal", en: "Bodyweight Squat" },
    { pt: "Box squat (agachamento no caixote)", en: "Box Squat" },
    { pt: "Agachamento overhead", en: "Overhead Squat" },
    { pt: "Agachamento zercher", en: "Zercher Squat" },
    { pt: "Afundo reverso com halteres", en: "Dumbbell Reverse Lunge" },
    { pt: "Afundo no smith", en: "Smith Machine Lunge" },
    { pt: "Leg press unilateral", en: "Single-Leg Press" },
    { pt: "Cadeira extensora unilateral", en: "Single-Leg Extension" },
    { pt: "Agachamento com salto", en: "Jump Squat" },
    { pt: "Cadeira adutora", en: "Hip Adduction Machine" },
  ],

  "Posterior de Coxa": [
    { pt: "Mesa flexora (lying leg curl)", en: "Lying Leg Curl" },
    { pt: "Cadeira flexora (seated leg curl)", en: "Seated Leg Curl" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Levantamento terra stiff", en: "Stiff-Leg Deadlift" },
    { pt: "Levantamento terra convencional", en: "Conventional Deadlift" },
    { pt: "Bom dia (good morning)", en: "Good Morning" },
    { pt: "Agachamento com barra baixa", en: "Low Bar Squat" },
    { pt: "Nordic curl (flexão nórdica)", en: "Nordic Ham Curl" },
    { pt: "Stiff com halteres", en: "Dumbbell Stiff-Leg Deadlift" },
    { pt: "Stiff com kettlebell", en: "Kettlebell Stiff-Leg Deadlift" },
    { pt: "Ponte de glúteos unilateral", en: "Single-Leg Glute Bridge" },
    { pt: "Flexão nórdica reversa", en: "Reverse Nordic Curl" },
    { pt: "Glute ham raise", en: "Glute Ham Raise" },
    { pt: "Levantamento terra sumô", en: "Sumo Deadlift" },
    { pt: "Pull-through na polia", en: "Cable Pull-Through" },
    { pt: "Slider leg curl", en: "Slider Leg Curl" },
    { pt: "Flexora em pé unilateral", en: "Standing Leg Curl" },
    { pt: "Flexora com bola suíça", en: "Swiss Ball Leg Curl" },
    { pt: "Reverse hyper (hiperextensão reversa)", en: "Reverse Hyperextension" },
    { pt: "Terra unilateral com kettlebell", en: "Single-Leg Romanian Deadlift" },
    { pt: "Good morning sentado", en: "Seated Good Morning" },
    { pt: "Kettlebell swing (foco posterior)", en: "Kettlebell Swing" },
    { pt: "Stiff no smith", en: "Smith Machine Stiff-Leg Deadlift" },
    { pt: "Deslize de posterior na plataforma", en: "Hamstring Slide" },
  ],

  "Glúteos": [
    { pt: "Agachamento livre com barra", en: "Barbell Back Squat" },
    { pt: "Levantamento terra romeno", en: "Romanian Deadlift" },
    { pt: "Hip thrust com barra", en: "Barbell Hip Thrust" },
    { pt: "Hip thrust na máquina", en: "Machine Hip Thrust" },
    { pt: "Ponte de glúteos", en: "Glute Bridge" },
    { pt: "Ponte de glúteos com barra", en: "Barbell Glute Bridge" },
    { pt: "Cable pull-through", en: "Cable Pull-Through" },
    { pt: "Avanço (lunge)", en: "Lunge" },
    { pt: "Agachamento búlgaro", en: "Bulgarian Split Squat" },
    { pt: "Step up com halteres", en: "Dumbbell Step-Up" },
    { pt: "Abdução de quadril na máquina", en: "Hip Abduction Machine" },
    { pt: "Abdução com faixa elástica", en: "Banded Hip Abduction" },
    { pt: "Clamshell com faixa", en: "Banded Clamshell" },
    { pt: "Donkey kick na polia", en: "Cable Donkey Kick" },
    { pt: "Fire hydrant", en: "Fire Hydrant" },
    { pt: "Coice na polia (cable kickback)", en: "Cable Glute Kickback" },
    { pt: "Agachamento sumô", en: "Sumo Squat" },
    { pt: "Kettlebell swing", en: "Kettlebell Swing" },
    { pt: "Coice na máquina (glute kickback)", en: "Glute Kickback Machine" },
    { pt: "Hip thrust unilateral", en: "Single-Leg Hip Thrust" },
    { pt: "Frog pump", en: "Frog Pump" },
    { pt: "Caminhada lateral com faixa", en: "Lateral Band Walk" },
    { pt: "Afundo cruzado (curtsy lunge)", en: "Curtsy Lunge" },
    { pt: "Abdução de quadril na polia", en: "Cable Hip Abduction" },
    { pt: "Extensão de quadril no banco (frog reverse hyper)", en: "Bench Hip Extension" },
    { pt: "Step-up alto (caixa alta)", en: "High Box Step-Up" },
  ],

  "Panturrilha": [
    { pt: "Elevação de panturrilha em pé (gêmeos)", en: "Standing Calf Raise" },
    { pt: "Elevação de panturrilha sentado", en: "Seated Calf Raise" },
    { pt: "Elevação de panturrilha no leg press", en: "Leg Press Calf Raise" },
    { pt: "Elevação de panturrilha no smith", en: "Smith Machine Calf Raise" },
    { pt: "Elevação de panturrilha unilateral em pé", en: "Single-Leg Standing Calf Raise" },
    { pt: "Elevação de panturrilha na máquina", en: "Calf Raise Machine" },
    { pt: "Elevação de panturrilha no degrau (step)", en: "Step Calf Raise" },
    { pt: "Elevação de panturrilha com halteres", en: "Dumbbell Calf Raise" },
    { pt: "Donkey calf raise", en: "Donkey Calf Raise" },
    { pt: "Elevação de panturrilha com barra", en: "Barbell Calf Raise" },
    { pt: "Saltos (jump rope)", en: "Jump Rope" },
    { pt: "Pogo jump", en: "Pogo Jump" },
    { pt: "Elevação de panturrilha no hack", en: "Hack Squat Calf Raise" },
    { pt: "Tibialis anterior raise", en: "Tibialis Anterior Raise" },
    { pt: "Panturrilha sentado com halter unilateral", en: "Single-Leg Seated Dumbbell Calf Raise" },
    { pt: "Panturrilha em pé sem carga", en: "Bodyweight Calf Raise" },
    { pt: "Calf press na máquina", en: "Machine Calf Press" },
    { pt: "Panturrilha balançante (rocking calf raise)", en: "Rocking Calf Raise" },
  ],

  "Trapézio": [
    { pt: "Encolhimento com barra (shrug)", en: "Barbell Shrug" },
    { pt: "Encolhimento com halteres", en: "Dumbbell Shrug" },
    { pt: "Encolhimento no smith", en: "Smith Machine Shrug" },
    { pt: "Encolhimento na máquina de encolhimento", en: "Shrug Machine" },
    { pt: "Encolhimento com kettlebell", en: "Kettlebell Shrug" },
    { pt: "Encolhimento com trap bar", en: "Trap Bar Shrug" },
    { pt: "Remada alta com barra", en: "Barbell Upright Row" },
    { pt: "Remada alta com halteres", en: "Dumbbell Upright Row" },
    { pt: "Face pull na polia", en: "Face Pull" },
    { pt: "Encolhimento na polia baixa", en: "Cable Shrug" },
    { pt: "Encolhimento por trás das costas", en: "Behind-the-Back Barbell Shrug" },
    { pt: "Farmer's walk", en: "Farmer's Walk" },
    { pt: "Overhead carry (caminhada acima da cabeça)", en: "Overhead Carry" },
    { pt: "Power clean", en: "Power Clean" },
    { pt: "Clean and press", en: "Clean and Press" },
    { pt: "Scaption com halteres", en: "Scaption" },
    { pt: "Remada alta na polia", en: "Cable Upright Row" },
    { pt: "High pull sumô com kettlebell", en: "Kettlebell Sumo High Pull" },
    { pt: "Retração escapular na barra fixa", en: "Scapular Pull-Up" },
    { pt: "Encolhimento inclinado com halteres", en: "Incline Dumbbell Shrug" },
    { pt: "Remada alta no smith", en: "Smith Machine Upright Row" },
  ],
};
